/** Tags geradas automaticamente a partir da legenda (não sobrescreve tags manuais futuras) */
export function detectPostTagsFromCaption(caption: string | null | undefined): string[] {
  if (!caption?.trim()) return [];

  const firstLine = caption.split("\n")[0]?.trim() ?? "";
  const haystack = `${firstLine}\n${caption}`;

  if (!/newsletter\s+bp\b/i.test(haystack)) return [];

  const tags: string[] = ["Newsletter"];

  const editionMatch = haystack.match(/edi[çc][ãa]o\s*#?\s*(\d+)/i);
  if (editionMatch?.[1]) {
    tags.push(`Edição #${editionMatch[1]}`);
  }

  return tags;
}

function isAutoGeneratedTag(tag: string): boolean {
  if (tag === "Newsletter") return true;
  return /^Edição #\d+$/.test(tag);
}

/** Mescla tags automáticas com tags já salvas, preservando tags manuais */
export function mergePostTags(
  autoTags: string[],
  existingTags: string[] | null | undefined
): string[] {
  const manual = (existingTags ?? []).filter((tag) => !isAutoGeneratedTag(tag));
  return [...new Set([...manual, ...autoTags])];
}

export function postHasTag(
  tags: string[] | null | undefined,
  tag: string
): boolean {
  return (tags ?? []).includes(tag);
}

export const KNOWN_AUTO_TAGS = ["Newsletter"] as const;
