import type { MarketingRequest } from "./marketing-requests";
import { AREAS, REQUEST_TYPES, STATUS_OPTIONS } from "./constants";

export type { MarketingRequest };
export { AREAS, REQUEST_TYPES, STATUS_OPTIONS };

const mockBase = {
  link: null as string | null,
  referencias: null as string | null,
  nome_advogado: null as string | null,
  assignee_id: null as string | null,
  workflow_stage: null as string | null,
  assignee_user: null as { name: string; avatar_url: string | null } | null,
  completion_type: null as "design_concluido" | "postagem_feita" | "conteudo_entregue" | null,
  priority: "normal" as const,
  deadline: null as string | null,
  stage_changed_at: null as string | null,
  solicitante_user: null as { name: string; department: string; avatar_url: string | null } | null,
};

export const MOCK_REQUESTS: MarketingRequest[] = [
  {
    id: "1",
    title: "Comunicado",
    description: "Arte para envio no Feedz sobre o benefício econômico mensal",
    requesting_area: "Trabalhista",
    status: "completed",
    requested_at: "2025-02-15T10:00:00Z",
    delivered_at: "2025-02-18T14:30:00Z",
    assignee: "Maria Silva",
    solicitante: "Renato Vallim",
    solicitante_id: null,
    request_type: "Comunicado",
    ...mockBase,
    workflow_stage: "concluido",
  },
  {
    id: "2",
    title: "PPT",
    description: "Arte de slides para cliente Levva",
    requesting_area: "Trabalhista",
    status: "in_progress",
    requested_at: "2025-02-20T09:00:00Z",
    delivered_at: null,
    assignee: "João Santos",
    solicitante: "Daniel Pressatto",
    solicitante_id: null,
    request_type: "PPT",
    ...mockBase,
    workflow_stage: "revisao",
  },
  {
    id: "3",
    title: "PPT",
    description: "Slides para apresentação interna",
    requesting_area: "Operações Legais",
    status: "completed",
    requested_at: "2025-02-25T11:00:00Z",
    delivered_at: "2025-02-26T10:00:00Z",
    assignee: "Ana Costa",
    solicitante: "Eduarda França Candido",
    solicitante_id: null,
    request_type: "PPT",
    ...mockBase,
    workflow_stage: "concluido",
  },
  {
    id: "4",
    title: "Post Redes Sociais",
    description: "Carrossel tema: STJ reafirma a preservação a empresa",
    requesting_area: "Reestruturação",
    status: "pending",
    requested_at: "2025-02-01T08:00:00Z",
    delivered_at: null,
    assignee: null,
    solicitante: "Ana Luiza",
    solicitante_id: null,
    request_type: "Post Redes Sociais",
    ...mockBase,
    workflow_stage: "tarefas",
  },
  {
    id: "5",
    title: "Aplicação de Identidade",
    description: "Capa linkedin",
    requesting_area: "Marketing",
    status: "completed",
    requested_at: "2025-02-10T14:00:00Z",
    delivered_at: "2025-02-14T10:00:00Z",
    assignee: "Maria Silva",
    solicitante: "Leonardo Marques",
    solicitante_id: null,
    request_type: "Aplicação de Identidade",
    ...mockBase,
    workflow_stage: "concluido",
  },
  {
    id: "6",
    title: "Comunicado",
    description: "Série de 5 posts sobre reforma trabalhista",
    requesting_area: "Trabalhista",
    status: "in_progress",
    requested_at: "2025-02-22T09:30:00Z",
    delivered_at: null,
    assignee: "João Santos",
    solicitante: "Daniel Pressatto",
    solicitante_id: null,
    request_type: "Comunicado",
    ...mockBase,
    workflow_stage: "revisado",
  },
  {
    id: "7",
    title: "Certificados",
    description: "Design de certificados para evento jurídico",
    requesting_area: "Cível",
    status: "pending",
    requested_at: "2025-02-28T10:00:00Z",
    delivered_at: null,
    assignee: null,
    solicitante: "Carlos Silva",
    solicitante_id: null,
    request_type: "Certificados",
    ...mockBase,
    workflow_stage: "tarefas",
  },
  {
    id: "8",
    title: "E-book",
    description: "Material visual para ebook sobre IRPF",
    requesting_area: "Societário e Contratos",
    status: "completed",
    requested_at: "2025-02-12T11:00:00Z",
    delivered_at: "2025-02-16T09:00:00Z",
    assignee: "Ana Costa",
    solicitante: "Fernanda Lima",
    solicitante_id: null,
    request_type: "E-book",
    ...mockBase,
    workflow_stage: "concluido",
  },
  {
    id: "9",
    title: "Campanha Março",
    description: "Materiais para campanha do mês",
    requesting_area: "Cível",
    status: "in_progress",
    requested_at: "2025-03-01T09:00:00Z",
    delivered_at: null,
    assignee: "Maria Silva",
    solicitante: "João Santos",
    solicitante_id: null,
    request_type: "Post Redes Sociais",
    ...mockBase,
    workflow_stage: "revisao_autor",
  },
  {
    id: "10",
    title: "Identidade Visual",
    description: "Atualização de elementos da identidade",
    requesting_area: "Marketing",
    status: "pending",
    requested_at: "2025-03-02T10:00:00Z",
    delivered_at: null,
    assignee: null,
    solicitante: "Leonardo Marques",
    solicitante_id: null,
    request_type: "Identidade Visual",
    ...mockBase,
    workflow_stage: "tarefas",
  },
];
