-- Reconhecimento facial opcional nas Fotos de eventos (processado no navegador).
--
-- LGPD: template facial é dado biométrico (sensível, art. 11). Só existe para quem
-- deu consentimento explícito em event_face_consents; revogar apaga referências,
-- correspondências e varreduras em cascata. Rostos de quem não aderiu são comparados
-- no navegador no momento do upload e descartados: nada deles é gravado aqui.
-- Todo acesso passa pelas rotas do servidor (service role); nenhuma leitura direta.

create table if not exists public.event_face_consents (
  user_id uuid primary key references public.users(id) on delete cascade,
  consent_version text not null,
  consented_at timestamptz not null default now()
);

create table if not exists public.event_face_consent_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  action text not null check (action in ('granted', 'revoked')),
  consent_version text,
  created_at timestamptz not null default now()
);

create index if not exists event_face_consent_log_user_idx
  on public.event_face_consent_log (user_id, created_at desc);

create table if not exists public.event_face_references (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.event_face_consents(user_id) on delete cascade,
  source_photo_id uuid references public.collaborator_photos(id) on delete set null,
  descriptor real[] not null check (array_length(descriptor, 1) = 128),
  created_at timestamptz not null default now()
);

create index if not exists event_face_references_user_idx
  on public.event_face_references (user_id);

create table if not exists public.event_photo_face_matches (
  photo_id uuid not null references public.event_photos(id) on delete cascade,
  user_id uuid not null references public.event_face_consents(user_id) on delete cascade,
  distance real not null check (distance >= 0),
  source text not null check (source in ('upload', 'self_scan')),
  rejected_at timestamptz,
  created_at timestamptz not null default now(),
  primary key (photo_id, user_id)
);

create index if not exists event_photo_face_matches_user_idx
  on public.event_photo_face_matches (user_id)
  where rejected_at is null;

create table if not exists public.event_face_album_scans (
  user_id uuid not null references public.event_face_consents(user_id) on delete cascade,
  album_id uuid not null references public.event_photo_albums(id) on delete cascade,
  scanned_at timestamptz not null default now(),
  primary key (user_id, album_id)
);

comment on table public.event_face_consents is
  'Opt-in do colaborador para encontrar suas fotos nos álbuns de eventos (dado biométrico, LGPD art. 11).';
comment on table public.event_face_consent_log is
  'Histórico de concessões e revogações do consentimento facial (prova de consentimento).';
comment on table public.event_face_references is
  'Templates faciais (128 números) gerados no navegador a partir das fotos corporativas de quem consentiu.';
comment on table public.event_photo_face_matches is
  'Fotos de eventos em que um colaborador que consentiu foi reconhecido. rejected_at = "não sou eu".';
comment on table public.event_face_album_scans is
  'Álbuns já varridos no navegador do colaborador em busca do próprio rosto.';

alter table public.event_face_consents enable row level security;
alter table public.event_face_consent_log enable row level security;
alter table public.event_face_references enable row level security;
alter table public.event_photo_face_matches enable row level security;
alter table public.event_face_album_scans enable row level security;

revoke all on public.event_face_consents from anon, authenticated;
revoke all on public.event_face_consent_log from anon, authenticated;
revoke all on public.event_face_references from anon, authenticated;
revoke all on public.event_photo_face_matches from anon, authenticated;
revoke all on public.event_face_album_scans from anon, authenticated;

grant all on public.event_face_consents to service_role;
grant all on public.event_face_consent_log to service_role;
grant all on public.event_face_references to service_role;
grant all on public.event_photo_face_matches to service_role;
grant all on public.event_face_album_scans to service_role;
grant usage, select on sequence public.event_face_consent_log_id_seq to service_role;
