CREATE TABLE public.official_photo_api_consumers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  name text NOT NULL,
  key_prefix text UNIQUE,
  key_hash text UNIQUE CHECK (key_hash IS NULL OR key_hash ~ '^[0-9a-f]{64}$'),
  allowed_scopes text[] NOT NULL DEFAULT ARRAY['photos:read']::text[],
  rate_limit_per_minute integer NOT NULL DEFAULT 300
    CHECK (rate_limit_per_minute BETWEEN 1 AND 10000),
  is_active boolean NOT NULL DEFAULT true,
  key_rotated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.official_photo_system_links (
  consumer_id uuid NOT NULL
    REFERENCES public.official_photo_api_consumers(id) ON DELETE CASCADE,
  external_user_id text NOT NULL CHECK (length(trim(external_user_id)) > 0),
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (consumer_id, external_user_id),
  UNIQUE (consumer_id, user_id)
);

CREATE INDEX official_photo_system_links_user_id_idx
  ON public.official_photo_system_links(user_id);

CREATE TABLE public.official_photo_api_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consumer_id uuid
    REFERENCES public.official_photo_api_consumers(id) ON DELETE SET NULL,
  route text NOT NULL,
  method text NOT NULL,
  status_code integer NOT NULL CHECK (status_code BETWEEN 100 AND 599),
  latency_ms integer NOT NULL CHECK (latency_ms >= 0),
  lookup_count integer NOT NULL DEFAULT 0 CHECK (lookup_count >= 0),
  requested_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX official_photo_api_requests_consumer_requested_idx
  ON public.official_photo_api_requests(consumer_id, requested_at DESC);

CREATE TABLE public.official_photo_api_rate_limits (
  consumer_id uuid NOT NULL
    REFERENCES public.official_photo_api_consumers(id) ON DELETE CASCADE,
  window_start timestamptz NOT NULL,
  request_count integer NOT NULL DEFAULT 0 CHECK (request_count >= 0),
  PRIMARY KEY (consumer_id, window_start)
);

ALTER TABLE public.official_photo_api_consumers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_photo_system_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_photo_api_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.official_photo_api_rate_limits ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.official_photo_api_consumers FROM anon, authenticated;
REVOKE ALL ON TABLE public.official_photo_system_links FROM anon, authenticated;
REVOKE ALL ON TABLE public.official_photo_api_requests FROM anon, authenticated;
REVOKE ALL ON TABLE public.official_photo_api_rate_limits FROM anon, authenticated;
GRANT ALL ON TABLE public.official_photo_api_consumers TO service_role;
GRANT ALL ON TABLE public.official_photo_system_links TO service_role;
GRANT ALL ON TABLE public.official_photo_api_requests TO service_role;
GRANT ALL ON TABLE public.official_photo_api_rate_limits TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.official_photo_api_requests_id_seq TO service_role;

CREATE OR REPLACE VIEW public.official_system_photos
WITH (security_invoker = true)
AS
SELECT
  u.id AS user_id,
  u.name,
  u.email,
  lower(trim(u.email)) AS normalized_email,
  selected.photo_id,
  COALESCE(selected.public_url, u.avatar_url) AS photo_url,
  CASE
    WHEN selected.photo_id IS NOT NULL THEN 'selected'
    WHEN u.avatar_url IS NOT NULL THEN 'legacy_avatar'
    ELSE 'none'
  END AS source,
  COALESCE(selected.updated_at, u.updated_at, now()) AS updated_at,
  md5(
    COALESCE(selected.public_url, u.avatar_url, '')
    || ':'
    || COALESCE(selected.updated_at, u.updated_at, now())::text
  ) AS version
FROM public.users u
LEFT JOIN LATERAL (
  SELECT
    cp.id AS photo_id,
    cp.public_url,
    cpu.updated_at
  FROM public.collaborator_photo_usages cpu
  JOIN public.photo_usage_types put
    ON put.id = cpu.usage_type_id
   AND put.is_official = true
  JOIN public.collaborator_photos cp
    ON cp.id = cpu.photo_id
   AND cp.user_id = cpu.user_id
  WHERE cpu.user_id = u.id
  LIMIT 1
) selected ON true
WHERE u.is_active IS NOT FALSE;

REVOKE ALL ON TABLE public.official_system_photos FROM anon, authenticated;
GRANT SELECT ON TABLE public.official_system_photos TO service_role;

CREATE OR REPLACE FUNCTION public.consume_official_photo_api_quota(p_consumer_id uuid)
RETURNS boolean
LANGUAGE plpgsql
VOLATILE
SET search_path = ''
AS $$
DECLARE
  current_window timestamptz := date_trunc('minute', now());
  allowed_limit integer;
  current_count integer;
BEGIN
  SELECT c.rate_limit_per_minute
    INTO allowed_limit
  FROM public.official_photo_api_consumers c
  WHERE c.id = p_consumer_id
    AND c.is_active = true;

  IF allowed_limit IS NULL THEN
    RETURN false;
  END IF;

  INSERT INTO public.official_photo_api_rate_limits (
    consumer_id,
    window_start,
    request_count
  )
  VALUES (p_consumer_id, current_window, 1)
  ON CONFLICT (consumer_id, window_start)
  DO UPDATE SET request_count =
    public.official_photo_api_rate_limits.request_count + 1
  RETURNING request_count INTO current_count;

  RETURN current_count <= allowed_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_official_photo_api_quota(uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_official_photo_api_quota(uuid)
  TO service_role;

INSERT INTO public.official_photo_api_consumers (slug, name)
VALUES
  ('responsum', 'Responsum'),
  ('sioe', 'SIOE')
ON CONFLICT (slug) DO UPDATE
SET
  name = excluded.name,
  updated_at = now();
